### ISSUE TITLE
MarkSearchResults is expensive during search

### ISSUE THREAD

**Issue by KirillOsenkov** [KirillOsenkov/MSBuildStructuredLog#319]
Marking the search results in the tree turns out to be very expensive during search.

There are a few things we could do.

1. Add a setting to toggle it on and off and set the default off. I've seen people ask what these dots are for and while I agree that it may be useful in some cases it doesn't seem to be warranted to be on by default.

2. Each result already has the node object when it is found - we could mark it as a result then and there, and avoid calling VisitAllChildren on an entire tree and do a lookup per result.

@ltrzesniewski let me know if you have some time looking into this. If not, that's OK.

**Comment by KirillOsenkov** [comment]
And here's a sample of how to add a setting:

https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/a47cc39d090a55d117fbb1abd4410a80821eb125/src/StructuredLogViewer.Core/SettingsService.cs#L306-L327

**Comment by KirillOsenkov** [comment]
Yeah it's pretty bad on large logs:

![image](https://user-images.githubusercontent.com/679326/77030736-da623b80-695c-11ea-845c-96b33cbb916d.png)

**Comment by KirillOsenkov** [comment]
Yes, I'm afraid we're going to need an option and have it off by default.

**Comment by ltrzesniewski** [comment]
I _think_ I have spotted some optimizations opportunities back when I was developing the feature, but I didn't want to change the code too much in order to keep the PR as simple as possible.

Now, I actually always rely on the dots to find my search results, I guess I'm biased but they're very useful IMO. If people don't know what they mean maybe adding a legend would be warranted?

Give me a few days, I'll see what I can do with this.

Just to make sure I reproduce this correctly, is tree virtualization disabled for in your example, or did you use a very large log? I'm asking since I don't think I've ever experienced search performance issues on the logs I work with.

**Comment by KirillOsenkov** [comment]
I have to support log sizes of 150MB and up :) Was testing on 37MB and 142MB. The biggest I have on my box is 480MB.

**Comment by ltrzesniewski** [comment]
Actually compiling the Roslyn project gives a nice 110 MB binlog. When searching for the string "build" in that binlog, the search takes roughly 11 seconds on my machine.

I reduced that to 7s for now. It takes 5s when `MarkSearchResults` is commented out. I'm pretty sure I can still improve on that. 😉

**Comment by KirillOsenkov** [comment]
Yes, I really want to optimize search as tightly as possible. 

One thing I was thinking of is parallelization.

Another idea is cancellation of previous searches.

Yet another idea is that if the previous query string is a strict prefix of the current query string, and we have the complete results from the previous search, we should just search through the results for the previous search, instead of searching through the entire tree. The idea here is that as you're typing you just keep narrowing the same initial results down.

Finally, the ultimate goal would be to build an index of the texts of the entire tree, so searching is really really fast. But I'm not sure that that would be warranted if we can make it fast enough.

**Comment by ltrzesniewski** [comment]
Yes, the search itself also can be surely optimized. I'll focus on the search results markers at first though, I'll try a few things. I hope I can make them basically free with the right implementation. 😉

I can take a look at the search itself once that problem is solved.

**Comment by KirillOsenkov** [comment]
@ltrzesniewski thanks for the PR! Impressive how you were able to remove most of the costs.

I profiled and made a few more fixes that should help with search performance a lot. I did make precomputing strings parallel and it was a nice improvement. I also found a surprising slow case of node.GetType().Name being very slow.

Unfortunately I've also found that search results still slow the search experience down in a few cases. Specifically if you have more than a 1000 results you still have to traverse the entire tree to update the markings. Also clearing the marks on the tree isn't cheap.

I've added an option to mark search results in the tree and disabled it by default. But if you check the checkbox it will persist so hopefully it won't cause any inconvenience. The search performance is paramount as a lot of people are routinely working with very large binlogs and every second we can save them counts.

Now that the search performance is back to what it was originally (and even better) I'm closing the issue. 

We can still keep thinking about how to optimize it further, possibly by building an index, but that can happen outside the scope of this issue.

Thanks!

**Comment by ltrzesniewski** [comment]
You're welcome :)

I also noticed the cost of `node.GetType().Name` in my profile traces, but I focused on the search markers for the PR.

I hoped the cost of traversing the whole tree would be low enough for searches limited to 1000 results... I suppose I could have added something like: "if you've reached max results, and if the node isn't marked as _contains search results_ then don't bother to traverse it further". Ah well, I guess your new option at least explains what the dots mean. 😉 

I think I'll still take a look at the search performance and see what I can do.

One question though: why are the `TreeNode` children of the `object` type instead of `BaseNode`? Constraining all nodes to `BaseNode` (and possibly merging `ParentedNode` into `BaseNode`) could enable more optimization opportunities, as the codebase currently contains **a lot** of type casts everywhere, which could be replaced by a virtual property on `BaseNode` which would return a `NodeType` enum (with a `NodeType.Other` item for node types defined by the viewer such as `ButtonNode`). Essentially what you did with `TypeName`, but with an enum instead.

Here's a profile trace from yesterday, I'm _guessing_ the unaccounted cost in `PopulateSearchFields` is entirely due to casting (this profile was made using tracing, not sampling):

![image](https://user-images.githubusercontent.com/7913492/77225017-7d88a000-6b6b-11ea-8774-2f17450b041a.png)

**Comment by KirillOsenkov** [comment]
Would be nice if you could look at search perf, anything helps.

I had another idea just now, also related to parallelization.

I’ll also check if I can switch to BaseNode from object, I’m guessing it’s for flexibility but it’s probably not warranted.

**Comment by KirillOsenkov** [comment]
FYI I just implemented parallel search and it seems to give a nice improvement.

**Comment by KirillOsenkov** [comment]
Found a few more nifty optimizations :) It's starting to look pretty good, but let me know if you spot anything else.

**Comment by ltrzesniewski** [comment]
Nice! I only took a quick look and tried to find some low hanging fruit, but didn't improve anything significantly.

My main idea is still to constrain all nodes to the `BaseNode` type, then add an enum to avoid all these casts. I may try to implement that quickly tomorrow to see if it helps.

**Comment by KirillOsenkov** [comment]
Yes, I'd be curious if getting rid of the casts will move the needle in any way. I have to say, I like casts because they make the system nicely extensible. But if we can show that there are non-trivial perf gains to be had, I'll always choose perf.

I also didn't look at the allocations much. I just added a Dictionary<,> in SearchResult and it's showing up. Thinking of eliminating that next, maybe just for a list of tuples.

**Comment by ltrzesniewski** [comment]
I tried my idea and it barely improved the performance. Increasing the code complexity for so little gain is not worth it.

I still have the change which replaces `object` with `BaseNode` though. Do you want a PR of this? It won't improve the speed in any way, it will just make the code more strongly typed.

Some other observations:

 - I also quickly tried the index approach in a _very_ crude way, and it seems promising: I got from 30s on my benchmark (using the current multi-threaded code) to 17s (single-threaded). The index I used is very simple: [result of `PopulateFields`] => [list of nodes]. My quick test was obviously incomplete so the real benefit could be different though.

 - I can confirm the code of that `Dictionary` you added in `SearchResult` is quite high. Removing `SearchResult.AddMatch` drops my benchmark time from 30s to 18s (or, in the case of the index above, from 17s to 9s). The list of tuples seems like a good idea. 👍

**Comment by KirillOsenkov** [comment]
If you already have the changes to switch to BaseNode, can you PR them so I can take a look at the code? If it's no trouble.

Nice. Your indexing experiment is interesting and I've love to see how you did it. I was planning to look into tokenizing words and prefix trees (sorted arrays), or even suffix trees, but the memory consumption is a concern there. Suffix trees allow you to find substrings that don't start at word boundaries, but usually are not worth it because people rarely search for "trings", they usually search for whole words such as "strings". Also suffix trees need an insane amount of memory.

And maybe even at some point in the future experiment with low-level stuff like this:
https://github.com/microsoft/elfie-arriba/blob/Cinco/Cinco/Cinco.Native/StringN.cpp

@ScottLouvau reports insane perf improvements from using these specialized instructions, especially if you need to search in a giant flat string. Maybe we could write out all the strings from the StringTable, 0-separated, with 7-bit encoded lengths, into a single giant UTF-8 byte array, and blaze through that using hardware acceleration.

Also I noticed that in the current approach HashSet lookups take a lot of time. If we somehow had the hashcodes for all strings precalculated we could make that significantly faster. Or maybe just store int indices into the StringTable, instead of storing actual strings. Maybe we need a StringTableEntry struct that wraps an integer and gets you a string or a hashcode cheaply.

**Comment by ltrzesniewski** [comment]
Ok, I'll send a PR for `BaseNode`.

Here's what I wrote as a simple test:

The index:

```C#
    public class SearchIndex
    {
        public Dictionary<string, List<BaseNode>> Index { get; } = new Dictionary<string, List<BaseNode>>();

        public SearchIndex(Build build)
        {
            Visit(build);
        }

        private void Visit(BaseNode node)
        {
            var values = NodeQueryMatcher.PopulateSearchFields(node);

            foreach (var value in values)
            {
                AddToIndex(node, value);
            }

            if (node is TreeNode treeNode && treeNode.HasChildren)
            {
                foreach (var child in treeNode.Children)
                {
                    Visit(child);
                }
            }
        }

        private void AddToIndex(BaseNode node, string value)
        {
            if (!Index.TryGetValue(value, out var nodeList))
            {
                nodeList = new List<BaseNode>();
                Index.Add(value, nodeList);
            }

            nodeList.Add(node);
        }
    }
```

The matching method in `NodeQueryMatcher`:

```C#
        public List<SearchResult> GetMatches(SearchIndex index)
        {
            var foundNodes = new HashSet<BaseNode>(ReferenceEqualityComparer<BaseNode>.Instance);

            foreach (var kvp in index.Index)
            {
                foreach (var word in Words)
                {
                    if (kvp.Key.IndexOf(word, StringComparison.OrdinalIgnoreCase) != -1)
                    {
                        foundNodes.UnionWith(kvp.Value);
                        break;
                    }
                }
            }

            var results = new List<SearchResult>(foundNodes.Count);

            foreach (var node in foundNodes)
            {
                var searchResult = new SearchResult(node);
                searchResult.AddMatch("foo", "bar"); // dummy data for this test
                results.Add(searchResult);
            }

            return results;
        }
```

It's nothing fancy and it's barely tested, but I'm getting the "same" result count as the normal method (it gives _one_ more item in the result set, which makes me think something may be missing in the string table).

Also I guess this takes a lot of memory, and you'd have to sort the results before displaying them (this would add to the total time, unless something better like storing the nodes in an ordered list and referring them by index is implemented).

I thought about tokenization, and indexing by letter trigrams packed into a tight struct (as the search requires at least 3 characters to start), but there would be edge cases that wouldn't be covered.

Caching the string hash codes seems like a good idea.

**Comment by KirillOsenkov** [comment]
I have implemented a balanced approach for string indexing (hard to point to a particular commit, but the main file is SearchIndex.cs.

It tries to balance memory consumption vs. speed. I have been testing it on a 1GB size binlog with 300 million nodes and 3.5 million strings. It gives 2-3 seconds per search worst case, but does increase memory consumption from 40 GB -> 60 GB roughly.
